{% set name = "django-extra-views" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7f8e07bd6c9388816a7c08d752661172d4078758c2079fc0cadddfcf5cd38ae3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >3.7
    - pip
  run:
    - python >3.7
    - django >=2.1

test:
  imports:
    - extra_views
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AndrewIngram/django-extra-views
  summary: Extra class-based views for Django
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
