{% set name = "django-extra-views" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django-extra-views-{{ version }}.tar.gz
  sha256: 2b9daf99c79e91035aa3f269232afcb3ccf837f0f49f2dc6da6916fe34bc1e0a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - django >=2.1

test:
  imports:
    - extra_views
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/AndrewIngram/django-extra-views
  summary: Extra class-based views for Django
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
